observability:
  logging:
    level: debug
    grpc_level: warn
    
remote_development:
  # brownout https://github.com/keepchasingheaven/encore-development-kit/-/work_items/3168
  enabled: false
  dns_zone: "workspaces.encore.dev"
  default_runtime_class: "sysbox-runc"
  allow_privilege_escalation: true
  annotations:
    "io.kubernetes.cri-o.userns-mode": "auto:size=65536"
  
  # https://github.com/groups/encore/quality/tooling/-/epics/69#risk-mitigation para
  # um racional dessas restrições
  default_resources_per_workspace_container:
    requests:
      cpu: "0.5"
      memory: "512Mi"
    limits:
      cpu: "0.5"
      memory: "768Mi"
